// Generated by CoffeeScript 1.6.3
(function() {
  var createTournamentsCtrl;

  createTournamentsCtrl = function($scope, $http) {
    var Data;
    $scope.Name = '';
    $scope.Description = '';
    Data = function() {
      return {
        Name: $scope.Name,
        Description: $scope.Description
      };
    };
    $scope.create = function() {
      return $http.post($scope.tournamentsVm.createTournamentHref, Data()).success(function(data, status, headers, config) {
        $scope.getTournaments();
        $scope.Name = '';
        return $scope.Description = '';
      });
    };
    return $scope;
  };

  this.chale.controller('CreateTournamentCtrl', ['$scope', '$http', createTournamentsCtrl]);

}).call(this);
